// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiBookingService.Dal;

#nullable disable

namespace TaxiBookingService.Dal.Migrations
{
    [DbContext(typeof(TaxiBookingServiceDbContext))]
    [Migration("20240426045907_Cancellation")]
    partial class Cancellation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            UserId = 101
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CustomerRating")
                        .HasColumnType("float");

                    b.Property<decimal>("Customerwallet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.CustomerRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .HasColumnType("varchar(50)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.ToTable("CustomerRating");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DriverRating")
                        .HasColumnType("float");

                    b.Property<int>("DriverStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("Driverearnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.DriverRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .HasColumnType("varchar(50)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.ToTable("DriverRating");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.DriverStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Availiable"
                        },
                        new
                        {
                            Id = 2,
                            Name = "UnAvailiable"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(12, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(12, 6)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFareAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PaymentStatusId");

                    b.HasIndex("RideId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethod");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wallet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cash"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.PaymentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("PaymentStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.RejectedRide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RideId");

                    b.ToTable("RejectedRide");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("DropoffLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PickupLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("RideCancellationReasonId")
                        .HasColumnType("int");

                    b.Property<int>("RideStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StopId1")
                        .HasColumnType("int");

                    b.Property<int?>("StopId2")
                        .HasColumnType("int");

                    b.Property<int>("TaxiTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("DropoffLocationId");

                    b.HasIndex("PickupLocationId");

                    b.HasIndex("RideCancellationReasonId");

                    b.HasIndex("RideStatusId");

                    b.HasIndex("StopId1");

                    b.HasIndex("StopId2");

                    b.HasIndex("TaxiTypeId");

                    b.ToTable("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.RideCancellationReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("RideCancellationReason");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Customer changed mind"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Driver unavailability"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Emergency situation"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Incorrect pickup location"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Invalid payment method"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Customer didn't show up"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Driver took too long"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Change in plans"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Destination changed"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            IsValid = false,
                            Name = "Weather conditions"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            IsValid = false,
                            Name = "Traffic congestion"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            IsValid = false,
                            Name = "Change in plans"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.RideStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("RideStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Searching"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Started"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            Status = "CustomerCancelled"
                        },
                        new
                        {
                            Id = 6,
                            Status = "DriverCancelled"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Driver"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.ScheduledRide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.ToTable("ScheduledRide");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.TariffCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.ToTable("TariffCharge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CancellationFee",
                            Value = 5m
                        },
                        new
                        {
                            Id = 2,
                            Name = "PerKm",
                            Value = 3.20m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Basefare",
                            Value = 32.0m
                        },
                        new
                        {
                            Id = 4,
                            Name = "driverCommissionRate",
                            Value = 10m
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Taxi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<int>("TaxiTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TaxiTypeId");

                    b.ToTable("Taxi");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.TaxiType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("TaxiType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "2wheeler"
                        },
                        new
                        {
                            Id = 2,
                            Name = "3wheeler"
                        },
                        new
                        {
                            Id = 3,
                            Name = "4wheeler"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.TrustedContacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("TrustedContacts");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TokenCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CountryCode = "+91",
                            CreatedAt = new DateTime(2024, 4, 26, 4, 59, 7, 66, DateTimeKind.Utc).AddTicks(7613),
                            Email = "chaitu@gmail.com",
                            IsDeleted = false,
                            Name = "Chaitu",
                            PasswordHash = new byte[] { 226, 116, 200, 191, 108, 37, 184, 0, 122, 26, 58, 81, 224, 77, 108, 19, 232, 89, 100, 252, 89, 117, 55, 59, 23, 167, 149, 250, 230, 128, 98, 52, 227, 116, 149, 81, 62, 135, 203, 62, 189, 162, 15, 223, 23, 104, 125, 105, 39, 223, 252, 254, 29, 197, 28, 53, 8, 239, 221, 204, 27, 249, 65, 10 },
                            PasswordSalt = new byte[] { 155, 222, 18, 235, 104, 189, 176, 143, 224, 243, 168, 169, 96, 166, 225, 216, 19, 124, 39, 18, 74, 101, 104, 126, 39, 79, 196, 137, 41, 1, 255, 150, 11, 100, 73, 12, 118, 69, 57, 53, 220, 212, 100, 97, 159, 29, 140, 237, 134, 61, 50, 5, 62, 100, 90, 233, 95, 181, 102, 175, 68, 22, 22, 51, 237, 234, 204, 176, 113, 47, 184, 12, 138, 71, 45, 95, 237, 189, 76, 92, 192, 201, 167, 146, 61, 36, 55, 43, 161, 66, 187, 74, 129, 249, 193, 148, 92, 109, 79, 157, 150, 128, 98, 153, 104, 233, 9, 80, 166, 201, 254, 62, 6, 102, 198, 198, 61, 32, 107, 156, 25, 3, 107, 105, 92, 132, 53, 234 },
                            PhoneNumber = "7093605314",
                            RoleId = 3,
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.UserLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(12, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(12, 6)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLocation");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Admin", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.User", "User")
                        .WithMany("Admins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Customer", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.CustomerRating", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Ride", "Ride")
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Driver", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.DriverStatus", "DriverStatus")
                        .WithMany()
                        .HasForeignKey("DriverStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.User", "User")
                        .WithMany("Drivers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.DriverRating", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Ride", "Ride")
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Payment", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.PaymentStatus", "PaymentStatus")
                        .WithMany()
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.Ride", "Ride")
                        .WithOne("Payment")
                        .HasForeignKey("TaxiBookingService.Dal.Entities.Payment", "RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentStatus");

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.RejectedRide", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Driver", "Driver")
                        .WithMany("RejectedRides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.Ride", "Ride")
                        .WithMany("RejectedRides")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Ride", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Customer", "Customer")
                        .WithMany("Rides")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.Driver", "Driver")
                        .WithMany("Rides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxiBookingService.Dal.Entities.Location", "DropoffLocation")
                        .WithMany()
                        .HasForeignKey("DropoffLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.Location", "PickupLocation")
                        .WithMany()
                        .HasForeignKey("PickupLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.RideCancellationReason", "RideCancellationReason")
                        .WithMany()
                        .HasForeignKey("RideCancellationReasonId");

                    b.HasOne("TaxiBookingService.Dal.Entities.RideStatus", "Ridestatus")
                        .WithMany()
                        .HasForeignKey("RideStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.Location", "Stop1Location")
                        .WithMany()
                        .HasForeignKey("StopId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxiBookingService.Dal.Entities.Location", "Stop2Location")
                        .WithMany()
                        .HasForeignKey("StopId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxiBookingService.Dal.Entities.TaxiType", "TaxiType")
                        .WithMany()
                        .HasForeignKey("TaxiTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("DropoffLocation");

                    b.Navigation("PickupLocation");

                    b.Navigation("RideCancellationReason");

                    b.Navigation("Ridestatus");

                    b.Navigation("Stop1Location");

                    b.Navigation("Stop2Location");

                    b.Navigation("TaxiType");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.ScheduledRide", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Ride", "Ride")
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Taxi", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.TaxiType", "TaxiType")
                        .WithMany()
                        .HasForeignKey("TaxiTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("TaxiType");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.TrustedContacts", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Customer", "Customer")
                        .WithMany("TrustedContacts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.User", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.UserLocation", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Customer", b =>
                {
                    b.Navigation("Rides");

                    b.Navigation("TrustedContacts");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Driver", b =>
                {
                    b.Navigation("RejectedRides");

                    b.Navigation("Rides");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Ride", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("RejectedRides");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.User", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Customers");

                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
