// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxiBookingService.Dal;

#nullable disable

namespace TaxiBookingService.Dal.Migrations
{
    [DbContext(typeof(TaxiBookingServiceDbContext))]
    [Migration("20240427112218_Admin")]
    partial class Admin
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Admin");

                    b.HasData(
                        new
                        {
                            Id = 3,
                            UserId = 101
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("CustomerRating")
                        .HasColumnType("float");

                    b.Property<decimal>("Customerwallet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PenaltyFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Customer");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.CustomerRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .HasColumnType("varchar(50)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.ToTable("CustomerRating");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<double?>("DriverRating")
                        .HasColumnType("float");

                    b.Property<int>("DriverStatusId")
                        .HasColumnType("int");

                    b.Property<decimal>("Driverearnings")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LicenceNumber")
                        .IsRequired()
                        .HasColumnType("varchar(16)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverStatusId");

                    b.HasIndex("UserId");

                    b.ToTable("Driver");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.DriverRating", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Feedback")
                        .HasColumnType("varchar(50)");

                    b.Property<float?>("Rating")
                        .HasColumnType("real");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.ToTable("DriverRating");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.DriverStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("DriverStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Availiable"
                        },
                        new
                        {
                            Id = 2,
                            Name = "UnAvailiable"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Location", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(12, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(12, 6)");

                    b.HasKey("Id");

                    b.ToTable("Location");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PaymentMethodId")
                        .HasColumnType("int");

                    b.Property<int>("PaymentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalFareAmount")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PaymentMethodId");

                    b.HasIndex("PaymentStatusId");

                    b.HasIndex("RideId")
                        .IsUnique();

                    b.ToTable("Payment");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.PaymentMethod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("PaymentMethod");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Wallet"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Cash"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.PaymentStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("PaymentStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Pending"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Completed"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshToken");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.RejectedRide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("RideId");

                    b.ToTable("RejectedRide");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Ride", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int?>("DriverId")
                        .HasColumnType("int");

                    b.Property<int>("DropoffLocationId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("PickupLocationId")
                        .HasColumnType("int");

                    b.Property<int?>("RideCancellationReasonId")
                        .HasColumnType("int");

                    b.Property<int>("RideStatusId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StopId1")
                        .HasColumnType("int");

                    b.Property<int?>("StopId2")
                        .HasColumnType("int");

                    b.Property<int>("TaxiTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("DriverId");

                    b.HasIndex("DropoffLocationId");

                    b.HasIndex("PickupLocationId");

                    b.HasIndex("RideCancellationReasonId");

                    b.HasIndex("RideStatusId");

                    b.HasIndex("StopId1");

                    b.HasIndex("StopId2");

                    b.HasIndex("TaxiTypeId");

                    b.ToTable("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.RideCancellationReason", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsValid")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("RideCancellationReason");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Customer changed mind"
                        },
                        new
                        {
                            Id = 2,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Driver unavailability"
                        },
                        new
                        {
                            Id = 3,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Emergency situation"
                        },
                        new
                        {
                            Id = 4,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Incorrect pickup location"
                        },
                        new
                        {
                            Id = 5,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Invalid payment method"
                        },
                        new
                        {
                            Id = 6,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Customer didn't show up"
                        },
                        new
                        {
                            Id = 7,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Driver took too long"
                        },
                        new
                        {
                            Id = 8,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Change in plans"
                        },
                        new
                        {
                            Id = 9,
                            IsDeleted = false,
                            IsValid = true,
                            Name = "Destination changed"
                        },
                        new
                        {
                            Id = 10,
                            IsDeleted = false,
                            IsValid = false,
                            Name = "Weather conditions"
                        },
                        new
                        {
                            Id = 11,
                            IsDeleted = false,
                            IsValid = false,
                            Name = "Traffic congestion"
                        },
                        new
                        {
                            Id = 12,
                            IsDeleted = false,
                            IsValid = false,
                            Name = "Change in plans"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.RideStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("RideStatus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Status = "Searching"
                        },
                        new
                        {
                            Id = 2,
                            Status = "Accepted"
                        },
                        new
                        {
                            Id = 3,
                            Status = "Started"
                        },
                        new
                        {
                            Id = 4,
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 5,
                            Status = "Cancelled"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.HasKey("Id");

                    b.ToTable("Role");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Customer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Driver"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.ScheduledRide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("RideId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RideId");

                    b.ToTable("ScheduledRide");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.TariffCharge", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal");

                    b.HasKey("Id");

                    b.ToTable("TariffCharge");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CancellationFee",
                            Value = 5m
                        },
                        new
                        {
                            Id = 2,
                            Name = "PerKm",
                            Value = 3.20m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Basefare",
                            Value = 32.0m
                        },
                        new
                        {
                            Id = 4,
                            Name = "driverCommissionRate",
                            Value = 10m
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Taxi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DriverId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("RegistrationNumber")
                        .IsRequired()
                        .HasColumnType("varchar(13)");

                    b.Property<int>("TaxiTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("TaxiTypeId");

                    b.ToTable("Taxi");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.TaxiType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.HasKey("Id");

                    b.ToTable("TaxiType");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "2wheeler"
                        },
                        new
                        {
                            Id = 2,
                            Name = "3wheeler"
                        },
                        new
                        {
                            Id = 3,
                            Name = "4wheeler"
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.TrustedContacts", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ContactName")
                        .IsRequired()
                        .HasColumnType("varchar(25)");

                    b.Property<string>("ContactPhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("TrustedContacts");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CountryCode")
                        .IsRequired()
                        .HasColumnType("varchar(5)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("TokenCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("TokenExpires")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CountryCode = "+91",
                            CreatedAt = new DateTime(2024, 4, 27, 11, 22, 17, 544, DateTimeKind.Utc).AddTicks(6695),
                            Email = "chaitu@gmail.com",
                            IsActive = false,
                            IsDeleted = false,
                            Name = "Chaitu",
                            PasswordHash = new byte[] { 206, 41, 50, 173, 127, 182, 32, 159, 160, 4, 84, 122, 53, 126, 55, 177, 180, 116, 136, 150, 177, 178, 81, 101, 159, 205, 69, 129, 191, 67, 191, 197, 9, 59, 134, 196, 65, 110, 156, 80, 158, 195, 171, 175, 136, 119, 172, 196, 203, 72, 180, 63, 52, 25, 14, 175, 199, 86, 136, 218, 143, 159, 65, 90 },
                            PasswordSalt = new byte[] { 190, 40, 69, 162, 164, 160, 170, 78, 232, 11, 13, 192, 212, 91, 26, 52, 150, 52, 47, 75, 114, 216, 13, 55, 185, 135, 68, 167, 23, 39, 113, 146, 32, 229, 122, 242, 39, 77, 87, 183, 141, 166, 34, 233, 249, 250, 88, 174, 169, 46, 9, 78, 53, 149, 42, 126, 151, 116, 1, 106, 57, 16, 103, 53, 145, 231, 195, 211, 235, 14, 82, 243, 203, 39, 15, 87, 1, 6, 244, 185, 44, 88, 130, 169, 37, 228, 70, 22, 147, 32, 73, 149, 189, 3, 120, 32, 241, 45, 97, 123, 178, 114, 184, 158, 6, 90, 245, 37, 35, 71, 96, 204, 69, 225, 94, 129, 125, 236, 162, 171, 182, 10, 164, 244, 190, 84, 87, 192 },
                            PhoneNumber = "7093605314",
                            RoleId = 1,
                            TokenCreated = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TokenExpires = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.UserLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(12, 6)");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(12, 6)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime2");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLocation");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Admin", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.User", "User")
                        .WithMany("Admins")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Customer", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.User", "User")
                        .WithMany("Customers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.CustomerRating", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Ride", "Ride")
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Driver", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.DriverStatus", "DriverStatus")
                        .WithMany()
                        .HasForeignKey("DriverStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.User", "User")
                        .WithMany("Drivers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DriverStatus");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.DriverRating", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Ride", "Ride")
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Payment", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.PaymentMethod", "PaymentMethod")
                        .WithMany()
                        .HasForeignKey("PaymentMethodId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.PaymentStatus", "PaymentStatus")
                        .WithMany()
                        .HasForeignKey("PaymentStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.Ride", "Ride")
                        .WithOne("Payment")
                        .HasForeignKey("TaxiBookingService.Dal.Entities.Payment", "RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PaymentMethod");

                    b.Navigation("PaymentStatus");

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.RejectedRide", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Driver", "Driver")
                        .WithMany("RejectedRides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.Ride", "Ride")
                        .WithMany("RejectedRides")
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Ride", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Customer", "Customer")
                        .WithMany("Rides")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.Driver", "Driver")
                        .WithMany("Rides")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxiBookingService.Dal.Entities.Location", "DropoffLocation")
                        .WithMany()
                        .HasForeignKey("DropoffLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.Location", "PickupLocation")
                        .WithMany()
                        .HasForeignKey("PickupLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.RideCancellationReason", "RideCancellationReason")
                        .WithMany()
                        .HasForeignKey("RideCancellationReasonId");

                    b.HasOne("TaxiBookingService.Dal.Entities.RideStatus", "Ridestatus")
                        .WithMany()
                        .HasForeignKey("RideStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.Location", "Stop1Location")
                        .WithMany()
                        .HasForeignKey("StopId1")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxiBookingService.Dal.Entities.Location", "Stop2Location")
                        .WithMany()
                        .HasForeignKey("StopId2")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("TaxiBookingService.Dal.Entities.TaxiType", "TaxiType")
                        .WithMany()
                        .HasForeignKey("TaxiTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Driver");

                    b.Navigation("DropoffLocation");

                    b.Navigation("PickupLocation");

                    b.Navigation("RideCancellationReason");

                    b.Navigation("Ridestatus");

                    b.Navigation("Stop1Location");

                    b.Navigation("Stop2Location");

                    b.Navigation("TaxiType");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.ScheduledRide", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Ride", "Ride")
                        .WithMany()
                        .HasForeignKey("RideId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ride");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Taxi", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Driver", "Driver")
                        .WithMany()
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaxiBookingService.Dal.Entities.TaxiType", "TaxiType")
                        .WithMany()
                        .HasForeignKey("TaxiTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");

                    b.Navigation("TaxiType");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.TrustedContacts", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Customer", "Customer")
                        .WithMany("TrustedContacts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.User", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.UserLocation", b =>
                {
                    b.HasOne("TaxiBookingService.Dal.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Customer", b =>
                {
                    b.Navigation("Rides");

                    b.Navigation("TrustedContacts");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Driver", b =>
                {
                    b.Navigation("RejectedRides");

                    b.Navigation("Rides");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.Ride", b =>
                {
                    b.Navigation("Payment")
                        .IsRequired();

                    b.Navigation("RejectedRides");
                });

            modelBuilder.Entity("TaxiBookingService.Dal.Entities.User", b =>
                {
                    b.Navigation("Admins");

                    b.Navigation("Customers");

                    b.Navigation("Drivers");
                });
#pragma warning restore 612, 618
        }
    }
}
